#!/usr/bin/env python3
"""
Seed the constructed Baltic Sea scenario into the three schema files' sample_records.
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

BASE = Path(__file__).parent.parent
sys.path.insert(0, str(BASE / "src"))

from pipeline.connectors.models import ColumnSchema, ExtractedSchema  # noqa: E402

SCHEMAS = BASE / "data" / "schemas"

# ── Anchor geography ────────────────────────────────────────────────────────
GDANSK = (54.3520, 18.6466)
KLAIPEDA = (55.7033, 21.1443)

# ── ACLED ───────────────────────────────────────────────────────────────────
# (id, date, disorder, event, sub_event, a1, inter1, a2, inter2, assoc1, assoc2,
#  civ_target, iso, country, admin1, location, lat, lon, fatalities, notes)
_ACLED = [
    (
        "POL1001",
        "2026-03-11",
        "Political violence",
        "Battles",
        "Armed clash",
        "Military Forces of Poland (2023-)",
        "State forces",
        "Unidentified Armed Group (Baltic)",
        "Rebels",
        "Naval Command of Poland",
        "",
        "",
        616,
        "Poland",
        "Pomorskie",
        "Gdansk",
        *GDANSK,
        3,
        "Armed clash reported in the port district of Gdansk.",
    ),
    (
        "POL1002",
        "2026-03-11",
        "Political violence",
        "Battles",
        "Armed clash",
        "Military Forces of Poland (2023-)",
        "State forces",
        "Unidentified Armed Group (Baltic)",
        "Rebels",
        "",
        "",
        "",
        616,
        "Poland",
        "Pomorskie",
        "Gdynia",
        54.5189,
        18.5305,
        1,
        "Exchange of fire near the naval base at Gdynia.",
    ),
    (
        "LTU1001",
        "2026-03-11",
        "Political violence",
        "Battles",
        "Armed clash",
        "Military Forces of Lithuania (2019-)",
        "State forces",
        "Unidentified Armed Group (Baltic)",
        "Rebels",
        "",
        "",
        "",
        440,
        "Lithuania",
        "Klaipedos",
        "Klaipeda",
        *KLAIPEDA,
        2,
        "Armed clash reported near the Klaipeda seaport.",
    ),
    (
        "POL1003",
        "2026-03-11",
        "Political violence",
        "Violence against civilians",
        "Attack",
        "Unidentified Armed Group (Baltic)",
        "Rebels",
        "Civilians (Poland)",
        "Civilians",
        "",
        "",
        "Civilian targeting",
        616,
        "Poland",
        "Pomorskie",
        "Gdansk",
        *GDANSK,
        1,
        "Civilians targeted in the same district later the same day.",
    ),
    (
        "LVA1001",
        "2026-03-11",
        "Demonstrations",
        "Protests",
        "Peaceful protest",
        "Protesters (Latvia)",
        "Protesters",
        "",
        "",
        "Dockworkers (Latvia)",
        "",
        "",
        428,
        "Latvia",
        "Riga",
        "Riga",
        56.9496,
        24.1052,
        0,
        "Peaceful demonstration held at the port of Riga.",
    ),
    (
        "EST1001",
        "2026-03-11",
        "Strategic developments",
        "Strategic developments",
        "Change to group/activity",
        "Military Forces of Estonia (2021-)",
        "State forces",
        "",
        "",
        "",
        "",
        "",
        233,
        "Estonia",
        "Harju",
        "Tallinn",
        59.4370,
        24.7536,
        0,
        "Reinforcement of coastal surveillance reported at Tallinn.",
    ),
    (
        "FIN1001",
        "2026-03-11",
        "Demonstrations",
        "Protests",
        "Peaceful protest",
        "Protesters (Finland)",
        "Protesters",
        "",
        "",
        "",
        "",
        "",
        246,
        "Finland",
        "Uusimaa",
        "Helsinki",
        60.1699,
        24.9384,
        0,
        "Demonstration held in central Helsinki.",
    ),
    (
        "SWE1001",
        "2026-03-11",
        "Strategic developments",
        "Strategic developments",
        "Other",
        "Military Forces of Sweden (2022-)",
        "State forces",
        "",
        "",
        "",
        "",
        "",
        752,
        "Sweden",
        "Stockholm",
        "Stockholm",
        59.3293,
        18.0686,
        0,
        "Naval readiness exercise announced.",
    ),
    (
        "DEU1001",
        "2026-03-11",
        "Demonstrations",
        "Protests",
        "Peaceful protest",
        "Protesters (Germany)",
        "Protesters",
        "",
        "",
        "",
        "",
        "",
        276,
        "Germany",
        "Mecklenburg-Vorpommern",
        "Rostock",
        54.0924,
        12.0991,
        0,
        "Protest held at the ferry terminal in Rostock.",
    ),
    (
        "LTU1002",
        "2026-03-11",
        "Demonstrations",
        "Riots",
        "Violent demonstration",
        "Rioters (Lithuania)",
        "Rioters",
        "Police Forces of Lithuania (2019-)",
        "State forces",
        "",
        "",
        "",
        440,
        "Lithuania",
        "Klaipedos",
        "Klaipeda",
        *KLAIPEDA,
        0,
        "Violent demonstration dispersed near the seaport.",
    ),
]

# ── ADS-B ───────────────────────────────────────────────────────────────────
# squawk carries the military/civilian code in the gold mapping: 77xx = military.
# (icao24, callsign, lat, lon, velocity, heading, vertrate, squawk, baro, geo, onground)
_ADSB = [
    (
        "ab58b2",
        "VIPER11",
        54.4010,
        18.7100,
        231.4,
        187.2,
        -2.5,
        "7777",
        430.0,
        452.6,
        False,
    ),
    (
        "3f7a21",
        "VIPER12",
        54.3801,
        18.6120,
        243.9,
        191.8,
        0.0,
        "7777",
        505.0,
        521.3,
        False,
    ),
    (
        "4841b9",
        "FALCON03",
        54.2900,
        18.5500,
        198.6,
        43.1,
        4.8,
        "7776",
        1180.0,
        1204.7,
        False,
    ),
    (
        "3e1f88",
        "VIPER13",
        54.3450,
        18.6300,
        252.7,
        176.4,
        -6.1,
        "7777",
        232.0,
        251.9,
        False,
    ),
    (
        "4d02f4",
        "RCH285",
        55.7180,
        21.1600,
        176.3,
        12.7,
        1.2,
        "7775",
        688.0,
        703.4,
        False,
    ),
    (
        "46b8c7",
        "VIPER21",
        59.9370,
        24.7556,
        268.1,
        88.9,
        0.0,
        "7777",
        461.0,
        479.8,
        False,
    ),
    (
        "47c1a2",
        "SAS1742",
        54.3600,
        18.6600,
        214.8,
        265.3,
        -3.4,
        "2451",
        9780.0,
        9822.5,
        False,
    ),
    (
        "4ca8f1",
        "LOT285",
        54.3300,
        18.6800,
        92.5,
        271.6,
        -7.9,
        "3421",
        288.0,
        302.1,
        False,
    ),
    (
        "3c65aa",
        "DLH88X",
        54.0924,
        12.0991,
        240.2,
        96.4,
        0.0,
        "1000",
        10970.0,
        11012.8,
        False,
    ),
    ("51cc3b", "", 56.9496, 24.1052, 187.9, 154.2, 2.1, "4567", 8460.0, 8503.7, False),
]

# ── MarineTraffic ───────────────────────────────────────────────────────────
# (mmsi, imo, shipname, callsign, flag, country, type_name, ais_summary, shiptype,
#  market, lat, lon, speed, course, heading, status, current_port, last_port, unlo, pcountry)
_MT = [
    (
        "261000101",
        "9701234",
        "ORP GENERAL PULASKI",
        "SPGP",
        "PL",
        "Poland",
        "Frigate",
        "Military",
        "35",
        "NAVAL",
        "54.3610",
        "18.6720",
        "84",
        "173",
        "175",
        "0",
        "",
        "GDYNIA",
        "PLGDY",
        "PL",
    ),
    (
        "261000102",
        "9701235",
        "ORP ORZEL",
        "SPOR",
        "PL",
        "Poland",
        "Submarine",
        "Military",
        "35",
        "NAVAL",
        "54.4880",
        "18.5410",
        "62",
        "8",
        "11",
        "0",
        "",
        "GDYNIA",
        "PLGDY",
        "PL",
    ),
    (
        "277000201",
        "9701236",
        "LNS ZEMAITIS",
        "LYZM",
        "LT",
        "Lithuania",
        "Corvette",
        "Military",
        "35",
        "NAVAL",
        "55.7120",
        "21.1290",
        "45",
        "354",
        "351",
        "0",
        "",
        "KLAIPEDA",
        "LTKLJ",
        "LT",
    ),
    (
        "265000301",
        "9701237",
        "HSWMS VISBY",
        "SAVB",
        "SE",
        "Sweden",
        "Corvette",
        "Military",
        "35",
        "NAVAL",
        "59.3410",
        "18.0920",
        "0",
        "0",
        "511",
        "5",
        "STOCKHOLM",
        "KARLSKRONA",
        "SEKAR",
        "SE",
    ),
    (
        "261000103",
        "9455102",
        "BALTIC TRADER",
        "SQEV",
        "PL",
        "Poland",
        "Container Ship",
        "Cargo",
        "70",
        "CONTAINERS",
        "54.3480",
        "18.6390",
        "112",
        "284",
        "287",
        "0",
        "GDANSK",
        "KLAIPEDA",
        "LTKLJ",
        "LT",
    ),
    (
        "277000202",
        "9145632",
        "NEMUNAS",
        "LYNM",
        "LT",
        "Lithuania",
        "General Cargo Ship",
        "Cargo",
        "70",
        "DRY BULK",
        "55.6940",
        "21.1610",
        "71",
        "66",
        "63",
        "0",
        "",
        "VENTSPILS",
        "LVVNT",
        "LV",
    ),
    (
        "219000401",
        "9377110",
        "DANA MAERSK",
        "OWDM",
        "DK",
        "Denmark",
        "Oil/Chemical Tanker",
        "Tanker",
        "80",
        "TANKERS",
        "55.6761",
        "12.5683",
        "126",
        "41",
        "44",
        "0",
        "",
        "AARHUS",
        "DKAAR",
        "DK",
    ),
    (
        "230000501",
        "9598344",
        "SUOMI EXPRESS",
        "OJPQ",
        "FI",
        "Finland",
        "Passenger/Ro-Ro Cargo Ship",
        "Passenger",
        "61",
        "RO-RO/PASSENGER",
        "60.1520",
        "24.9210",
        "198",
        "179",
        "181",
        "0",
        "",
        "HELSINKI",
        "FIHEL",
        "FI",
    ),
    (
        "276000601",
        "9288041",
        "EESTI STAR",
        "ESES",
        "EE",
        "Estonia",
        "General Cargo Ship",
        "Cargo",
        "70",
        "DRY BULK",
        "59.4410",
        "24.7480",
        "88",
        "263",
        "265",
        "0",
        "",
        "TALLINN",
        "EETLL",
        "EE",
    ),
    (
        "211000701",
        "9210447",
        "ROSTOCK CARRIER",
        "DHRC",
        "DE",
        "Germany",
        "Ro-Ro Cargo Ship",
        "Cargo",
        "70",
        "RO-RO",
        "54.1050",
        "12.1180",
        "104",
        "12",
        "15",
        "0",
        "ROSTOCK",
        "TRELLEBORG",
        "SETRG",
        "SE",
    ),
]

_DAY = "2026-03-11"


def acled_rows() -> list[dict]:
    rows = []
    for i, (
        eid,
        date,
        dis,
        ev,
        sub,
        a1,
        i1,
        a2,
        i2,
        as1,
        as2,
        civ,
        iso,
        country,
        adm1,
        loc,
        lat,
        lon,
        fat,
        notes,
    ) in enumerate(_ACLED):
        ts = int(
            datetime.datetime.fromisoformat(
                f"{date}T{8 + i:02d}:15:00+00:00"
            ).timestamp()
        )
        rows.append(
            {
                "event_id_cnty": eid,
                "event_date": date,
                "year": 2026,
                "time_precision": 1,
                "disorder_type": dis,
                "event_type": ev,
                "sub_event_type": sub,
                "actor1": a1,
                "assoc_actor_1": as1,
                "inter1": i1,
                "actor2": a2,
                "assoc_actor_2": as2,
                "inter2": i2,
                "interaction": f"{i1} - {i2}" if i2 else i1,
                "civilian_targeting": civ,
                "iso": iso,
                "region": "Europe",
                "country": country,
                "admin1": adm1,
                "admin2": loc,
                "admin3": "",
                "location": loc,
                "latitude": lat,
                "longitude": lon,
                "geo_precision": 1,
                "source": "Baltic Monitoring Desk",
                "source_scale": "Subnational",
                "notes": notes,
                "fatalities": fat,
                "tags": "",
                "timestamp": ts,
                "population_1km": 1500.0,
                "population_2km": 4200,
                "population_5km": 31000,
                "population_best": 1500.0,
            }
        )
    return rows


def adsb_rows() -> list[dict]:
    rows = []
    for i, (icao, cs, lat, lon, vel, hdg, vr, sq, baro, geo, ong) in enumerate(_ADSB):
        rows.append(
            {
                "time": f"{_DAY} {8 + i:02d}:20:00+00:00",
                "icao24": icao,
                "lat": lat,
                "lon": lon,
                "velocity": vel,
                "heading": hdg,
                "vertrate": vr,
                "callsign": cs,
                "onground": ong,
                "squawk": sq,
                "baroaltitude": baro,
                "geoaltitude": geo,
            }
        )
    return rows


def mt_rows() -> list[dict]:
    rows = []
    for i, (
        mmsi,
        imo,
        name,
        cs,
        flag,
        country,
        tname,
        summ,
        stype,
        market,
        lat,
        lon,
        spd,
        course,
        hdg,
        status,
        cport,
        lport,
        lunlo,
        lpcountry,
    ) in enumerate(_MT):
        stamp = f"{_DAY}T{8 + i:02d}:25:00.000Z"
        rows.append(
            {
                "mmsi": mmsi,
                "imo": imo,
                "ship_id": f"90{i:04d}",
                "lat": lat,
                "lon": lon,
                "speed": spd,
                "heading": hdg,
                "course": course,
                "status": status,
                "timestamp": stamp,
                "dsrc": "TER" if i % 2 == 0 else "SAT",
                "utc_seconds": str(10 + i),
                "market": market,
                "shipname": name,
                "shiptype": stype,
                "callsign": cs,
                "flag": flag,
                "length": str(90 + i * 11),
                "width": f"{12 + i}.50",
                "grt": str(3200 + i * 900),
                "dwt": str(4100 + i * 1300),
                "draught": str(48 + i * 3),
                "year_built": str(2005 + i),
                "ship_country": country,
                "ship_class": "",
                "rot": "0",
                "type_name": tname,
                "ais_type_summary": summ,
                "destination": lunlo,
                "eta": f"{_DAY}T{14 + i:02d}:00:00.000Z",
                "l_fore": str(20 + i),
                "w_left": str(6 + i),
                "current_port": cport,
                "last_port": lport,
                "last_port_time": f"2026-03-10T{12 + i:02d}:00:00.000Z",
                "current_port_id": "1074" if cport else "",
                "current_port_unlocode": "PLGDN" if cport else "",
                "current_port_country": "PL" if cport else "",
                "last_port_id": str(1200 + i),
                "last_port_unlocode": lunlo,
                "last_port_country": lpcountry,
                "next_port_id": "",
                "next_port_unlocode": "",
                "next_port_name": "",
                "next_port_country": "",
                "eta_calc": "",
                "eta_updated": "",
                "distance_to_go": str(i * 7),
                "distance_travelled": str(40 + i * 13),
                "avg_speed": f"{9 + i * 0.4:.1f}",
                "max_speed": f"{13 + i * 0.5:.1f}",
            }
        )
    return rows


def write(path: Path, rows: list[dict], source_type: str, dry: bool) -> None:
    old = ExtractedSchema.model_validate(json.loads(path.read_text()))
    names = [c.name for c in old.columns]
    missing = [n for n in names if n not in rows[0]]
    extra = [k for k in rows[0] if k not in names]
    assert not missing, f"{path.name}: seeded rows miss columns {missing}"
    assert not extra, f"{path.name}: seeded rows add unknown columns {extra}"
    new = ExtractedSchema(
        source_name=old.source_name,
        source_type=source_type, # type: ignore
        columns=[ColumnSchema(**c.model_dump()) for c in old.columns],
        inferred_fields=old.inferred_fields,
        sample_records=[{n: r[n] for n in names} for r in rows],
        extraction_timestamp=datetime.datetime.now(),
    )
    if dry:
        print(
            f"  [dry-run] {path.name}: would write {len(rows)} rows x {len(names)} columns"
        )
        return
    path.write_text(json.dumps(new.model_dump(), indent=4, default=str) + "\n")
    print(f"  {path.name}: {len(rows)} rows x {len(names)} columns")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    print("Seeding the constructed Baltic scenario (SYNTHETIC DATA):")
    write(SCHEMAS / "postgres_schema.json", acled_rows(), "relational", args.dry_run)
    write(SCHEMAS / "timescale_schema.json", adsb_rows(), "timeseries", args.dry_run)
    write(SCHEMAS / "marinetraffic_schema.json", mt_rows(), "timeseries", args.dry_run)


if __name__ == "__main__":
    main()
